agregar grafico
celinadelturco/Login pull request #1
Opened 2024-01-25 00:20 UTC by celinadelturco

Agregué un gráfico de barra

2024-01-26 00:18 UTC, emendoza96 requested changes
Nota

2024-01-26 00:18 UTC, emendoza96 commented on login.html
> +            if (user === "celina" && password === "1234") {
Estaría bueno que simules una base de datos usando un arreglo de usuarios. Tambien tendrías que comprobar si alguno de los usuarios en tu array coincide el par user/password para loguearte.

Por ejemplo:
```javascript
let listaUsuarios = [];

// agrego usuario 1
listaUsuarios.push({user: "celina", password: "1234"});
// agrego usuario 2
listaUsuarios.push({user: "emi", password: "5678"}) 
````

2024-01-26 14:17 UTC, celinadelturco commented on login.html
> +            if (user === "celina" && password === "1234") {
Gracias por la idea, en estos días la voy a implementar. Debería convertir todos los caracteres del usuario a minúscula? O que haga diferencia en el nombre de usuario si hay alguna mayúscula?

2024-02-04 16:38 UTC, emendoza96 commented
Esto ya está listo?

2024-02-04 21:52 UTC, celinadelturco commented
@emendoza96 Está listo, pero tengo un problema al intentar agregar un gráfico. No queda como me gustaría. En un rato hago el commit con los cambios solicitados.

2024-02-08 21:51 UTC, emendoza96 approved these changes

2024-02-08 21:51 UTC, merged